apiVersion: v1
kind: ConfigMap
metadata:
{{- with .Values.configMap }}
  name: {{ .name }}
  namespace: {{ .namespace }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}