apiVersion: apps/v1
kind: Deployment
metadata:
{{- with .Values }}
  labels:
{{ include "brand-chart.labels" $ | indent 4 }}
  name: {{ .appName }}
  namespace: {{ .namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .appName }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
    spec:
      containers:
        - name: {{ .appName }}
          image: {{ .image.repository }}
          ports:
            - containerPort: {{ .containerPort }}
{{- end }}
          env: 
          {{- include "brand-chart.env" . | nindent 10 }}
      restartPolicy: Always