apiVersion: v1
entries:
  brand-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-10-07T20:04:46.16704-04:00"
    description: A Helm chart for Kubernetes
    digest: dfe820e63f3fe1feeac42ccec01f5cdece1205f83d5a42e7b4edc9a900db1049
    name: brand-chart
    type: application
    urls:
    - brand-chart-0.1.0.tgz
    version: 0.1.0
generated: "2023-10-07T20:04:46.166444-04:00"
