apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "brandrouter.fullname" . }}-secrets"
  namespace: {{ .Values.brand }}
data:
  APOLLO_KEY: {{ .Values.secrets.apollo_router.APOLLO_KEY | b64enc }}
