apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "brandrouter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: apollo
      protocol: TCP
      name: http
  selector:
    app: {{ include "brandrouter.fullname" . }}
