name: Copy rhai scripts to router chart 
on: 
  push:
    branches:
      - "main"
    paths:
      - "./app/rhai/**

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - id: "checkout"
        uses: actions/checkout@v3

      - name: Copy rhai directory to router Helm chart
        run: |
          cp -R ./app/rhai ./copied
        shell: bash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated update to Helm chart rhai scripts