name: Helm template test

on:
  push:
    branches:
      - *
    paths:
      - "infrastructure/kubernetes/helm"

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run helm template
        working-directory: infrastructure/kubernetes/helm
        run: |
          find . -type f -name "Chart.yaml" -print0 | while IFS=0 read -r -d '' file; 
            do dir=$(dirname "$file")
            echo "Running helm template in $dir"
            (cd "$dir" && helm template . --debug)
          done
