apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brand-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jbutcher93/platform.git
    targetRevision: main
    path: charts/brands 
    helm:
      valueFiles: 
        - values.yaml
      releaseName: nginx
  destination:
    server: https://kubernetes.default.svc #on the same cluster, so we can use the internal address
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
